# Build and push Docker image to docker hub

name: Build

on:
  push:
    branches:
      - "main"
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-push:
    name: Build docker image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: kapitan
      PLATFORMS: linux/amd64,linux/arm64

    steps:
      # This step uses Github's checkout-action: https://github.com/actions/checkout
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            eu.gcr.io/quortex-registry-public/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      # Login if the event is a push or a tag to be able to push
      - name: Login to GCR
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      # Always build the docker image, and push it on merge or tag
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
